

### 获取推荐的文章
GET http://localhost:5000/articles/isRecommend HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiYWRtaW4iLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJhZG1pbiIsImV4cCI6MTYyODQzMzE5OSwiaXNzIjoiamhnIn0.SESVvy5LA4WyT5a8QiU1lNjJXXbcKWEvKNRqb6KyXEs



### 获取指定文章
GET http://localhost:5000/articles/2 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiYWRtaW4iLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJhZG1pbiIsImV4cCI6MTYyODQzMzE5OSwiaXNzIjoiamhnIn0.SESVvy5LA4WyT5a8QiU1lNjJXXbcKWEvKNRqb6KyXEs

### 点赞
POST http://localhost:5000/likes HTTP/1.1
Content-Type: application/json

{
    "UserId":2,
    "ArticleId":1
}

### 评论
POST http://localhost:5000/Comments HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiYWRtaW4iLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJhZG1pbiIsImV4cCI6MTYyODQzMzE5OSwiaXNzIjoiamhnIn0.SESVvy5LA4WyT5a8QiU1lNjJXXbcKWEvKNRqb6KyXEs
Content-Type: application/json

{
    "FromUserId":2,
    "ToUserId":1,
    "ArticleId":1,
    "Comment":"hhh"
}

###   修改文章浏览量
PUT http://localhost:5000/articles/putRead/1 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiYWRtaW4iLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJhZG1pbiIsImV4cCI6MTYyODQzMzE5OSwiaXNzIjoiamhnIn0.SESVvy5LA4WyT5a8QiU1lNjJXXbcKWEvKNRqb6KyXEs
Content-Type: application/json

{
    
}

### 通过文章id获取指定评论
GET http://localhost:5000/comments/2 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiYWRtaW4iLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJhZG1pbiIsImV4cCI6MTYyODQzMzE5OSwiaXNzIjoiamhnIn0.SESVvy5LA4WyT5a8QiU1lNjJXXbcKWEvKNRqb6KyXEs
