### 登录获取token
POST http://localhost:5000/users/token HTTP/1.1
Content-Type: application/json

{
    "username":"admin",
    "password":"123"
}

### 刷新重新获取token
POST http://localhost:5000/users/refreshtoken HTTP/1.1
Content-Type: application/json

{
    "token":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiYWRtaW4iLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJhZG1pbiIsImV4cCI6MTYyNTU2MjM4MywiaXNzIjoiV29vWiJ9.bey_PEfjXxFQ192VAP1YFuK8LKsw4NhFgkT4n32Zce0",
    "refreshtoken":"123235"
}

### 查询所有用户
GET http://localhost:5000/users?currentPage=1&pageSize=5 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiYWRtaW4iLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJhZG1pbiIsImV4cCI6MTY2MjE0MjMwNCwiaXNzIjoiamhnIn0.qRWm_TLf9tF9k7bi6JtHKJQO0SzU-2O_UvygXqztZWI

### 根据id获取用户
GET  http://localhost:5000/users/3 HTTP/1.1
Authorization:  Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiYWRtaW4iLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJhZG1pbiIsImV4cCI6MTY2MDQ4OTExOSwiaXNzIjoiamhnIn0.FjjgEnkm9KrKrRVtOxz42zTb9OyXl1MB5ACZago_c0s

### 根据输入框的内容 查询对应的用户
POST http://localhost:5000/Users/queryUser HTTP/1.1
Content-Type: application/json
Authorization:  Bearer  eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiYWRtaW4iLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJhZG1pbiIsImV4cCI6MTY2MTczNDkwNywiaXNzIjoiamhnIn0.-bYvz4LqpLA0iTkUxmFO1oB6hU0Myc3hsklJQit7Tc0

{
    "username":"a",
    "currentPage":1,
    "pageSize":5
}

###  创建用户
POST http://localhost:5000/Users HTTP/1.1
Content-Type: application/json
Authorization:  Bearer  eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiYWRtaW4iLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJhZG1pbiIsImV4cCI6MTY2MjM4NTIzOSwiaXNzIjoiamhnIn0.GwlwDCbArMOuads07Z2oW6gqOfAxHMaaVPJd05AltGQ

{
    "username":"uuu",
    "password":"123",
    "remarks":"",
    "UserRoleId":2,
    "AvatarUrl":""
}

###   修改用户信息
PUT http://localhost:5000/users/2 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiYWRtaW4iLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJhZG1pbiIsImV4cCI6MTY2MDU3NjIxMywiaXNzIjoiamhnIn0.9qjxNMp0op3geFViWU614L6jWE9PFi-1oG08RpCOuZo
Content-Type: application/json

{
    "username":"uu",
    "password":"123",
    "remarks":"修改头像",
    "UserRoleId":2,
    "AvatarUrl":""
}

###  根据id删除用户
DELETE http://localhost:5000/users/2 HTTP/1.1





### 注册
POST http://localhost:5000/Register/ HTTP/1.1
Content-Type: application/json

{
   "username":"小鹿",
   "password":"123",
   "checkPass":"123",
   "userRoleId" :2
}


### 获取推荐的文章
GET http://localhost:5000/articles/isRecommend HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiYWRtaW4iLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJhZG1pbiIsImV4cCI6MTYyODQzMzE5OSwiaXNzIjoiamhnIn0.SESVvy5LA4WyT5a8QiU1lNjJXXbcKWEvKNRqb6KyXEs



### 获取指定文章
GET http://localhost:5000/articles/2 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiYWRtaW4iLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJhZG1pbiIsImV4cCI6MTYyODQzMzE5OSwiaXNzIjoiamhnIn0.SESVvy5LA4WyT5a8QiU1lNjJXXbcKWEvKNRqb6KyXEs

### 点赞
POST http://localhost:5000/likes HTTP/1.1
Content-Type: application/json

{
    "UserId":2,
    "ArticleId":1
}

### 评论
POST http://localhost:5000/Comments HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiYWRtaW4iLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJhZG1pbiIsImV4cCI6MTYyODQzMzE5OSwiaXNzIjoiamhnIn0.SESVvy5LA4WyT5a8QiU1lNjJXXbcKWEvKNRqb6KyXEs
Content-Type: application/json

{
    "FromUserId":2,
    "ToUserId":1,
    "ArticleId":1,
    "Comment":"hhh"
}

###   修改文章浏览量
PUT http://localhost:5000/articles/putRead/1 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiYWRtaW4iLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJhZG1pbiIsImV4cCI6MTYyODQzMzE5OSwiaXNzIjoiamhnIn0.SESVvy5LA4WyT5a8QiU1lNjJXXbcKWEvKNRqb6KyXEs
Content-Type: application/json

{
    
}

### 通过文章id获取指定评论
GET http://localhost:5000/comments/2 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiYWRtaW4iLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJhZG1pbiIsImV4cCI6MTYyODQzMzE5OSwiaXNzIjoiamhnIn0.SESVvy5LA4WyT5a8QiU1lNjJXXbcKWEvKNRqb6KyXEs
